# Generated by Django 4.0.3 on 2022-03-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='full_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
